spring:
  datasource:
    url: jdbc:postgresql://dpg-ct6rc9d2ng1s73973hig-a.oregon-postgres.render.com/nails_back
    username: root
    password: XMzGUy6jF5Lge0Nwj3OjO6h9mkNyClWz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
  web:
    cors:
      mappings:
        "/nails/**":
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

# Configuración personalizada
path_mapping: "/nails_back"
path_cross: "*"
max_page: 9

