# Conexión a MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/js_nails_db?createDatabaseIfNotExist=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: off
  web:
    cors:
      mappings:
        "/nails/**":
          allowed-origins: "http://localhost:5173"
          allowed-methods: "*"
          allowed-headers: "*"

# Configuración personalizada
path_mapping: nails
page_max: 9
